// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/register": {
            "post": {
                "description": "Receives user and organization registration data together and returns confirmation message",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Registration"
                ],
                "parameters": [
                    {
                        "description": "Combined registration payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegistrationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.OrganizationRegisterRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "Savska cesta 123, Zagreb"
                },
                "email": {
                    "type": "string",
                    "example": "info@mshop.hr"
                },
                "name": {
                    "type": "string",
                    "example": "mShop d.o.o."
                },
                "oib": {
                    "type": "string",
                    "example": "12345678901"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+38515555555"
                }
            }
        },
        "models.RegistrationRequest": {
            "type": "object",
            "properties": {
                "organization": {
                    "$ref": "#/definitions/models.OrganizationRegisterRequest"
                },
                "user": {
                    "$ref": "#/definitions/models.UserRegisterRequest"
                }
            }
        },
        "models.UserRegisterRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "Savska cesta 14, Zagreb"
                },
                "date_of_birth": {
                    "type": "string",
                    "example": "1990-05-20"
                },
                "email": {
                    "type": "string",
                    "example": "ivan@example.com"
                },
                "first_name": {
                    "type": "string",
                    "example": "Ivan"
                },
                "is_admin": {
                    "type": "boolean",
                    "example": true
                },
                "last_name": {
                    "type": "string",
                    "example": "Ivić"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+38599111222"
                },
                "username": {
                    "type": "string",
                    "example": "ivan.ivic"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Account Service API",
	Description:      "API documentation for the account service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
