basePath: /
definitions:
  handlers.RefreshRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  models.LoginRequest:
    properties:
      password:
        example: test123456
        minLength: 6
        type: string
      username:
        example: ivan.ivic
        minLength: 6
        type: string
    required:
    - password
    - username
    type: object
  models.OrganizationRegisterRequest:
    properties:
      address:
        example: Savska cesta 123, Zagreb
        minLength: 10
        type: string
      email:
        example: info@mshop.hr
        type: string
      name:
        example: mShop d.o.o.
        minLength: 3
        type: string
      oib:
        example: "12345678901"
        type: string
      phone_number:
        example: "+38515555555"
        type: string
    required:
    - address
    - email
    - name
    - oib
    - phone_number
    type: object
  models.RegistrationRequest:
    properties:
      organization:
        $ref: '#/definitions/models.OrganizationRegisterRequest'
      user:
        $ref: '#/definitions/models.UserRegisterRequest'
    type: object
  models.UserRegisterRequest:
    properties:
      address:
        example: Savska cesta 14, Zagreb
        minLength: 10
        type: string
      date_of_birth:
        example: "1990-05-20"
        type: string
      email:
        example: ivan@example.com
        type: string
      first_name:
        example: Ivan
        minLength: 3
        type: string
      is_admin:
        example: true
        type: boolean
      last_name:
        example: Ivić
        minLength: 3
        type: string
      phone_number:
        example: "+38599111222"
        type: string
      username:
        example: ivan.ivic
        minLength: 6
        type: string
    required:
    - address
    - date_of_birth
    - email
    - first_name
    - last_name
    - phone_number
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: API documentation for the account service
  title: Account Service API
  version: "1.0"
paths:
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: Receives username/password, returns access + refresh token
      parameters:
      - description: User login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user
      tags:
      - Authentication
  /api/v1/refresh:
    post:
      consumes:
      - application/json
      description: Generate new access token using refresh token
      parameters:
      - description: Refresh token payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.RefreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Refresh access token
      tags:
      - Authentication
  /api/v1/register:
    post:
      consumes:
      - application/json
      description: Receives user and organization registration data together and returns
        confirmation message
      parameters:
      - description: Combined registration payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.RegistrationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - Registration
swagger: "2.0"
