FROM golang:1.25-alpine

WORKDIR /app
COPY . .

WORKDIR /app/mshop-transactions-service

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o transactions-service cmd/main.go

ENV GIN_MODE=debug
EXPOSE 8080
CMD ["./transactions-service"]
