services:
  account-service:
    container_name: account-service
    build:
      context: ./mshop-account-service
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=account-db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=account_db
    depends_on:
      - account-db
    networks:
      - app-network

  account-db:
    image: postgres:15
    container_name: account-db
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - account-db-data:/var/lib/postgresql/data

  goose-account:
    build:
      context: .
      dockerfile: goose/Dockerfile
    depends_on:
      - account-db
    volumes:
      - ./migrations/account:/migrations
    entrypoint: [ "goose" ]
    working_dir: /migrations
    networks:
      - app-network

  transactions-service:
    container_name: transactions-service
    build:
      context: ./mshop-transactions-service
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=transactions-db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=transactions_db
    depends_on:
      - transactions-db
    networks:
      - app-network

  transactions-db:
    image: postgres:15
    container_name: transactions-db
    environment:
      POSTGRES_DB: transactions_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - app-network
    volumes:
      - transactions-db-data:/var/lib/postgresql/data

  goose-transactions:
    build:
      context: .
      dockerfile: goose/Dockerfile
    depends_on:
      - transactions-db
    volumes:
      - ./migrations/transactions:/migrations
    entrypoint: [ "goose" ]
    working_dir: /migrations
    networks:
      - app-network

  articles-service:
    container_name: articles-service
    build:
      context: ./mshop-articles-service
      dockerfile: Dockerfile.dev
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=articles-db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=articles_db
    depends_on:
      - articles-db
    networks:
      - app-network

  articles-db:
    image: postgres:15
    container_name: articles-db
    environment:
      POSTGRES_DB: articles_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    networks:
      - app-network
    volumes:
      - articles-db-data:/var/lib/postgresql/data

  goose-articles:
    build:
      context: .
      dockerfile: goose/Dockerfile
    depends_on:
      - articles-db
    volumes:
      - ./migrations/articles:/migrations
    entrypoint: [ "goose" ]
    working_dir: /migrations
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  account-db-data:
  transactions-db-data:
  articles-db-data: