FROM golang:1.25-alpine

WORKDIR /app
COPY . .

WORKDIR /app/mshop-account-service

COPY mshop-account-service/cmd/.env .env

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o account-service cmd/main.go

ENV GIN_MODE=debug
EXPOSE 8080
CMD ["./account-service"]
