FROM golang:1.24-alpine AS builder

RUN apk add --no-cache git
RUN go install github.com/go-delve/delve/cmd/dlv@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o articles-service cmd/main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/articles-service .
COPY --from=builder /go/bin/dlv /dlv

EXPOSE 8001 40000 9000

CMD ["/dlv", "--headless", "--listen=:40000", "--api-version=2", "exec", "./articles-service"]
